/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.news;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction; 
import net.tiaozhanbei.model.News;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.NewsConst;


import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;




/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="failed" path="/Web/Manage/NewsManage/AddFail.jsp"
 * @struts.action-forward name="success" path="/Web/Manage/NewsManage/AddSuccess.jsp"
 */
public class AddNewsAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private News news = new News();
	private static final Log log = LogFactory.getLog(AddNewsAction.class);
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){

		User author = (User)request.getSession().getAttribute("user");
		Date time = new Date();

		if (author != null) {
			this.news.setAuthor(author);
			this.news.setCatagory(request.getParameter("catagory"));
			this.news.setTime(time);
			request.getSession().setAttribute("time", time);
			this.news.setTitle(request.getParameter("title"));
			this.news.setType(NewsConst.Type.NORMAL);
			this.news.setPicPath(request.getParameter("picpath"));
			BuildHTML buildHTML = new BuildHTML();
			try {
				this.news.setUrl(buildHTML.generateNews(request, response));
			} catch (Exception e) {
				log.error("generate HTML file failed");
				request.setAttribute("message", "fail");
			}
			try {
				getNewsService().addNews(this.news);
			} catch (Exception e) {
				log.error("add news failed");
				request.setAttribute("message", "fail");
			}
				
			request.setAttribute("message", "success");
		} else {
			log.error("right check failed!!!");
			request.setAttribute("message", "fail");
		}
		return mapping.findForward("ajaxSuccessOrFailure");
	}	
}