/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.news;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction; 
import net.tiaozhanbei.model.News;


import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;




/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="failed" path="/Web/Manage/NewsManage/AddFail.jsp"
 * @struts.action-forward name="success" path="/Web/Manage/NewsManage/AddSuccess.jsp"
 */
public class SetHeadNewsAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private News news = new News();
	private static final Log log = LogFactory.getLog(SetHeadNewsAction.class);
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
				String newsID = request.getParameter("newsid");
				if (newsID == null) {
					log.error("set HeadNews failed");
					request.setAttribute("message", "fail");
				} else {
					log.debug("set headnews");
					news = getNewsService().findNewsById(Integer.parseInt(newsID));
					getNewsService().setHeadNews(news);
					request.setAttribute("message", "success");
				}
				return mapping.findForward("ajaxSuccessOrFailure");
	}
}