/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.form.passWordForm;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.Sha512DigestUtils;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-08-2009
 * 
 * XDoclet definition:
 * @struts.action input="/Web/Manage/UserManage/PassWordChange.jsp" validate="true"
 * @struts.action-forward name="manage" path="/Web/Manage/Manage.jsp"
 * @struts.action-forward name="error" path="/Web/errorPage.jsp"
 */
public class PassWordChangeAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		passWordForm regForm=(passWordForm) form;
		HttpSession session=request.getSession();
		User user=(User) session.getAttribute("user");
		if (user!=null) {		//如果用户已经登陆
		String oldPassWord1=user.getPassword();
		String oldPassWord2=Sha512DigestUtils.shaHex(regForm.getOldpassword());
		if (oldPassWord1.equals(oldPassWord2)){
			System.out.println("老密码"+regForm.getOldpassword()+"新密码"+regForm.getPassword());
			String newPassWord=request.getParameter("newpassword");
			System.out.println("新密码"+newPassWord);
			newPassWord=Sha512DigestUtils.shaHex(newPassWord);
			user.setPassword(newPassWord);
			System.out.println("将要修改密码"+user.getPassword());
			if(getUserService().updateUser(user)){
			session.removeAttribute("user");
			session.setAttribute("user",user);
			request.setAttribute("message", "success");//如果修改成功，回到后台管理页面
			}else{
				request.setAttribute("message", "Modify failed!");
			}
		} else {
			request.setAttribute("message", "Old Password Wrong!");
		}
		}else {
			request.setAttribute("message", "Not Login");
		}
		
		return mapping.findForward("ajaxSuccessOrFailure");
		
	}
}