/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.form.RegisterForm;
import net.tiaozhanbei.model.User;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/userEdit" name="editForm" input="/Web/Manage/UserManage/_Edit.jsp" scope="request" validate="true"
 */
public class UserEditAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm editForm = (RegisterForm) form;
		HttpSession session=request.getSession();
		User user=(User)session.getAttribute("user");//从session中读取用户之前的信息
		user.setEmail(editForm.getEmail());//以下几步将用户修改的信息添加到用户对象内
		user.setDepartment(editForm.getDepartment());
		user.setPhone(editForm.getPhone());
		user.setRealName(editForm.getRealName());
		System.out.println("真实姓名"+user.getRealName());
		user.setSex(editForm.getSex());
		if (getUserService().updateUser(user)) {
			session.removeAttribute("user");//将原来的用户信息从session中移走
			session.setAttribute("user",user);//将更新过的用户信息更新进session中
			System.out.println("执行完毕");
			request.setAttribute("message", "success");
			
		} else {
				request.setAttribute("message", "failure");
		}
		return mapping.findForward("ajaxSuccessOrFailure");
	}
}