/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.User;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/verifyUser" name="editForm" input="/Web/Manage/UserManage/VerifyUser.jsp" parameter="from" scope="request" validate="true"
 */
public class VerifyAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//负责提取被审核的用户的所有信息
		
		int userId=Integer.valueOf(request.getParameter("userId"));
		User noVerifyUser=getUserService().getUserById(userId);
		if (noVerifyUser!=null) {
			request.setAttribute("noVerifyUser",noVerifyUser);
			return mapping.findForward("verifyOperate");
			
		}
		else
		return mapping.findForward("error");
	}
}