/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.User;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.Logger;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class FileManageAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private Logger logger=Logger.getLogger(getClass());
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String action=request.getParameter("action");
		logger.info("file_action:"+action);
		if(action==null){
            request.setAttribute("message", "please select what you do!");
            return mapping.findForward("error");
        }
        if(action.equals("list")){
           // System.out.print("list:");
        	User  user=(User)request.getSession().getAttribute("user");
            //System.out.print("user_id:"+user.getId());
            request.setAttribute("list",getFileInfoService().list_author(user.getId()));
            return mapping.findForward("list");
        }else return mapping.findForward("upload");
	}
}