/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-22-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class LetterManageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String action=(String)request.getParameter("action");
		System.out.println("letterManage:"+action);
		if(action.equals("send")){
			request.setAttribute("receiverId",request.getParameter("receiverId"));//��request��õ�������id
		}
		request.setAttribute("action", action);
		return mapping.findForward(action);
	}
}