/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage;

import java.util.List;
import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.News;
import net.tiaozhanbei.util.CommonResources;
import net.tiaozhanbei.util.Page;
import net.tiaozhanbei.util.datastruct.UrlTree;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class NewsManageAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	ResourceBundle bundle= CommonResources.getNewsCatagoryBundle();
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String action=request.getParameter("action");
        if(action==null){
        	
            request.setAttribute("message", "please select what you do!");
            return mapping.findForward("error");
            
        } else if (action.equals("listNews")){
        	
        	Page<News> newsPage = new Page<News>(request.getParameter("page"));
    		getNewsService().fillPageByAll(newsPage);
    		request.setAttribute("newsPage", newsPage);
    		System.out.print(newsPage.getPageSize());
    		return mapping.findForward("listNews");
    		
        } else if (action.equals("addNews")) {
        	
        	UrlTree tree = UrlTree.load("newsCatagory", bundle);
        	request.setAttribute("catagoryTree", tree);
        	return mapping.findForward("addNews");
        	
        } else if (action.equals("listAnnonce")){
        	
        	List<News> newsList;
        	newsList = getNewsService().getAnounce();
        	request.setAttribute("annonceList", newsList);
        	return mapping.findForward("listAnnonce");
        	
        } else if (action.equals("addAnnonce")) {
        	
        	return mapping.findForward("addAnnonce");
        	
        } else 
        	return mapping.findForward("error");
	}
	
}