/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.util.CommonResources;
import net.tiaozhanbei.util.datastruct.UrlTree;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-14-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserManageAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String forward=request.getParameter("right");
		System.out.println("UserManage TO:"+forward);
		UrlTree tree = UrlTree.load("projectCatagory", CommonResources.getProjectCatagoryBundle());
		request.setAttribute("catagoryTree", tree);
		return mapping.findForward(forward);			
	}
}