/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.project;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import net.tiaozhanbei.action.*;
import net.tiaozhanbei.util.CommonResources;
import net.tiaozhanbei.util.datastruct.UrlTree;

/** 
 * MyEclipse Struts
 * Creation date: 03-20-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ProjectInfoAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id = Integer.parseInt(request.getParameter("id"));
		request.setAttribute("project",
				getProjectService().getProject(id));
		UrlTree tree = UrlTree.load("projectCatagory", CommonResources.getProjectCatagoryBundle());
		request.setAttribute("catagoryTree", tree);
		return mapping.findForward("success");
		
	}
}