/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.project;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.form.ProjectForm;
import net.tiaozhanbei.model.Project;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.UserConst;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.beans.BeanUtils;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2009
 * 
 * XDoclet definition:
 * @struts.action path="/regProject" name="projectRegForm" scope="request" validate="true"
 */
public class RegProjectAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	//实现项目注册，只有已经是作者的用户可以进行此操作
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ProjectForm projectRegForm = (ProjectForm) form;// TODO Auto-generated method stub
		HttpSession session=request.getSession();
		User user=(User)session.getAttribute("user");
		if(user!=null&&user.getType()==UserConst.Type.AUTHOR){//如果是作者用户并且已登陆
			Project project=new Project();
			BeanUtils.copyProperties(projectRegForm, project);//转换为项目模型
			/*if (getUserService().regProject(user,project)) {
				return mapping.findForward("");
				
			}*/
			
		}
		
		
		
		
		return null;
	}
}