/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.letter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-21-2009
 * 
 * XDoclet definition:
 * @struts.action parameter="letterId" validate="true"
 */
public class DelLetterAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		/* action:send ,receive表示动作
		 * letterId:信件
		 */
		
		try{
			getLetterService().del(Integer.parseInt(request.getParameter("letterId")),(String)request.getParameter("action"));
			request.setAttribute("message", "success");
		}catch (Exception e) {

			request.setAttribute("messsage", "deleteFailed!");
		}
		return mapping.findForward("ajaxSuccessOrFailure");
	}
}