/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.letter;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.Letter;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.Logger;

/** 
 * MyEclipse Struts
 * Creation date: 03-21-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
	public class LetterAction extends BaseAction {
	/* 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
		Logger logger=Logger.getLogger(getClass());
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		/*letterId:查看的信件
		 * action:表示查看动作
		 */
		Letter letter=new Letter();
		letter.setId(Integer.parseInt(request.getParameter("letterId")));
		
		letter=getLetterService().view(letter);
		logger.debug("letter_id:"+letter.getId());
		logger.debug("letter_title:"+letter.getTitle());
		request.setAttribute("letter", letter);
		return mapping.findForward("view");
	}
}