/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.letter;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.Letter;
import net.tiaozhanbei.model.User;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-21-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SendLetterAction extends BaseAction {
	/*
	 * Generated Methods
	 */
	private static Logger logger = Logger.getLogger(SendLetterAction.class);
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		// TODO Auto-generated method stub
		/* 信件标题：title
		 * 信件内容：content
		 * 接受者:receiverName 或 receiverId
		 */
		try{
		Letter letter=new Letter();
		letter.setChecked(0);
		letter.setContent(request.getParameter("content"));
		letter.setTitle(request.getParameter("title"));
		letter.setState(0);
		letter.setTime(new Date());
		
		User sender=(User)request.getSession().getAttribute("user");
		User receiver=new User();
		
		String receiverId = request.getParameter("receiverId");
		String receiverName = request.getParameter("receiverName");
		
		logger.info(receiverId);
		logger.info(receiverName);
		if(receiverId!=null && !"null".equals(receiverId) && !"".equals(receiverId))
			receiver.setId(Integer.parseInt(receiverId));
		if(receiverName!=null && !"null".equals(receiverName) && !"".equals(receiverName))
			receiver = getUserService().getUserByName(receiverName);
		
		letter.setSender(sender);
		letter.setReceiver(receiver);
			getLetterService().send(letter);
			request.setAttribute("message", "success");
		}catch (Exception e) {
			request.setAttribute("message", e.getMessage());
		}
		
		return mapping.findForward("ajaxSuccessOrFailure");
	}
}