/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.vote;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.exception.DAOException;
import net.tiaozhanbei.form.NewVoteForm;
import net.tiaozhanbei.model.Vote;
import net.tiaozhanbei.model.VoteItem;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
/** 
 * MyEclipse Struts
 * Creation date: 03-19-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AddvoteAction extends BaseAction {
	/*
	 * Generated Methods
	 */
	static Logger logger = Logger.getLogger(AddvoteAction.class);
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException 
	 */
	@SuppressWarnings("unchecked")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {


		NewVoteForm voteForm = (NewVoteForm)form;
		Vote vote = new Vote();
		vote.setDescription(voteForm.getDiscription());

		logger.info(voteForm.getDiscription());
		vote.setEnable(true);
		vote.setTitle(voteForm.getTitle());
		vote.setType( voteForm.getType());
		String[] choices = voteForm.getChoices();
		logger.info("choices="+choices.length);
		for (int i = 0; i < choices.length; i++) {
			if(!"".equals(choices[i])){
				VoteItem item = new VoteItem();
				item.setContent(choices[i]);
				vote.getVoteItems().add(item);
			}
		}try{
			getVoteService().addVote(vote);
			request.setAttribute("message","success");
		}catch (DAOException e) {
			request.setAttribute("message", "failed");
		}
		return mapping.findForward("ajaxSuccessOrFailure");
	}
	
}