/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.manage.vote;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ModifyAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward switchEnable(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int voteId = Integer.parseInt(request.getParameter("voteId"));
		String messageString="success";
		try{
			getVoteService().switchEnable(voteId);
		}catch (Exception e) {
			messageString = "failure";
		}
		request.setAttribute("message", messageString);
		return mapping.findForward("ajaxSuccessOrFailure");
	}
	
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int voteId = Integer.parseInt(request.getParameter("voteId"));
		String messageString="success";
		try{
			getVoteService().delVote(voteId);
		}catch (Exception e) {
			messageString = "failure";
		}
		request.setAttribute("message", messageString);
		return mapping.findForward("ajaxSuccessOrFailure");
	}
}