/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.form.regAuthorAndProjectForm;
import net.tiaozhanbei.model.Project;
import net.tiaozhanbei.model.User;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-03-2009
 * 
 * XDoclet definition:
 * @struts.action path="/authorReg" name="projectRegForm" input="/Web/Register/AuthorRegister.jsp" scope="request" validate="true"
 */
public class AuthorRegAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		regAuthorAndProjectForm regForm=(regAuthorAndProjectForm)form;
		
		Project project=new Project();
		User user=new User();		
		try {
			System.out.println("开始执行作者注册的Action!");
			project.setBrief(regForm.getBrief());
			project.setName(regForm.getName());
			project.setType(String.valueOf(regForm.getType()));		
			user=(User)request.getSession().getAttribute("user");
			user.setPhone(regForm.getPhone());
			user.setRealName(regForm.getRealName());
			user.setDepartment(regForm.getDepartment());
			System.out.println("开始执行作者注册的Action!");
			System.out.println("从session中得到的用户"+user.getName()+user.getRegisterTime());
			System.out.println("project:"+project.getName()+project.getBrief());
			//System.out.println("ownerID:"+project.getOwner().getId());
			if(getUserService().registerAuthor(user, project))
				return mapping.findForward("index");

	
		
			
		} catch (Exception e) {
			System.out.println(e);
			return mapping.findForward("error");
		}
		return mapping.findForward("error");
	}
}