/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.form.MoreUserInfoForm;
import net.tiaozhanbei.model.User;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-01-2009
 * 
 * XDoclet definition:
 * @@struts.action path="/companyReg" name="regForm" input="/Web/Register/CompanyReg.jsp" scope="request" validate="true"
 */
public class CompanyRegAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @@param mapping
	 * @@param form
	 * @@param request
	 * @@param response
	 * @@return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MoreUserInfoForm regForm=(MoreUserInfoForm)form;
		
		// TODO Auto-generated method stub
		HttpSession session=request.getSession();//获得session
		User user=(User) session.getAttribute("user");//从session中获得之前注册的用户信息
		user.setDepartment(regForm.getDepartment());//将企业用户的新信息加进去
		user.setRealName(regForm.getRealName());
		user.setPhone(regForm.getPhone());
		if(getUserService().registerMoreUserInfo(user))
			return mapping.findForward("index");
		else 		
		return mapping.findForward("error");
	}
}
