/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.model.User;
import net.tiaozhanbei.action.*;
import net.tiaozhanbei.form.MoreUserInfoForm;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-01-2009
 * 
 * XDoclet definition:
 * @@struts.action path="/judgerReg" name="regForm" input="/Web/Register/JudgerReg.jsp" scope="request" validate="true"
 */
public class JudgerRegAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @@param mapping
	 * @@param form
	 * @@param request
	 * @@param response
	 * @@return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();//ªÒ»°session
		User user=(User)session.getAttribute("user");
		MoreUserInfoForm regForm=(MoreUserInfoForm)form;
		
		try {
			BeanUtils.copyProperties(user, regForm);
			
		} catch (Exception e) {
			// TODO: handle exception
			return mapping.findForward("error");
		}
		
		if(getUserService().registerMoreUserInfo(user))
			return mapping.findForward("index");
		else		
		return mapping.findForward("error");
	}
}
