/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.user;



import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.*;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.Page;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="list" path="/Web/Manage/FileManage/file_list.jsp"
 * @struts.action-forward name="upload" path="/Web/Manage/FileManage/file_upload.jsp"
 */
public class NoVerifyUserAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		String page=request.getParameter("page");
		Page<User>  userList=new Page<User>(page);
			getUserService().fillPageByNoVerify(userList);
		request.setAttribute("userlist",userList);		
		return mapping.findForward("verifyUserList");
	}
}