/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.user;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.User;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
/** 
 * MyEclipse Struts
 * Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="UserInfo" path="/UserInfo.jsp"
 */
public class UserInfoAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id=Integer.valueOf(request.getParameter("id"));
		System.out.println("In Actoin,Before getUserService.checkUserInfo" + new Date());
		User userInfo = getUserService().checkUserInfo(id);
		System.out.println("读取用户信息："+userInfo.getDepartment()+userInfo.getPassword()+userInfo.getRealName());

		request.setAttribute("userInfo",userInfo);
		return mapping.findForward("userInfo");
	}
}