/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.user;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.UserConst;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.Logger;

/** 
 * MyEclipse Struts
 * Creation date: 03-06-2009
 * 
 * XDoclet definition:
 * @struts.action input="/Web/Manage/UserManage/VerifyUser.jsp" validate="true"
 * @struts.action-forward name="index" path="/Web/Index/index.jsp"
 * @struts.action-forward name="error" path="/Web/errorPage.jsp"
 */
public class VerifyResultAction extends BaseAction {
	/*
	 * Generated Methods
	 */
	private Logger logger = Logger.getLogger(VerifyResultAction.class);
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int userId=Integer.valueOf(request.getParameter("userId"));//获取正在审核的用户ID
		String isVerify=request.getParameter("isVerify");//获取审核结果，false是未通过审核，true是通过审核
		User userVerify=getUserService().getUserById(userId);
		User user=(User)(request.getSession()).getAttribute("user");
		logger.info(("管理员用户信息"+user.getName()+user.getType()));
		if(user==null||user.getType()!=UserConst.Type.MANAGER)
			return mapping.findForward("error");
		if(userVerify!=null)
		{
			boolean ok = "true".equals(isVerify);
			logger.info(("审核开始"));
			getUserService().verifyUser(userVerify,ok);
			request.setAttribute("message", "success");
			
		}
		else request.setAttribute("message", "failure");
		
		return mapping.findForward("ajaxSuccessOrFailure");
		
		
		
	}
}