/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.project;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.form.ProjectCommentForm;
import net.tiaozhanbei.model.Letter;
import net.tiaozhanbei.model.ProjectComment;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.ProjectCommentConst;
import net.tiaozhanbei.util.UserConst;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-01-2009
 * 
 * XDoclet definition:
 * @struts.action path="/project/addComment" name="projectCommentForm" scope="request" validate="true"
 */
public class AddCommentAction extends BaseAction{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ProjectCommentForm projectCommentForm = (ProjectCommentForm) form;// TODO Auto-generated method stub
		int projectId=Integer.parseInt(request.getParameter("projectId"));
		String iswriteback=request.getParameter("writeback");
		HttpSession session=request.getSession();
		String receivername=request.getParameter("receivername");
		String url=request.getParameter("url");
		Date date=new Date();
		User user=(User)session.getAttribute("user");
		if(user==null){
			user=new User();
			user.setName("游客");
		}
		System.out.println(iswriteback);
		if("true".equals(iswriteback)&&!receivername.equals("游客"))//如果不是回复游客
		{
			User receiver=getUserService().getUserByName(receivername);		
			
			String letterContent="尊敬的用户:\n用户 \""+user.getName()+"\""+"在项目页"+url+"中回复了您的评论。";
			System.out.println(letterContent);
			User sender;
			
			 sender=getUserService().getUserByName("admin");
			
			Letter letter=new Letter();
			letter.setChecked(0);
			letter.setState(0);
			letter.setTime(date);
			letter.setSender(sender);
			letter.setTitle("系统通知");
			letter.setContent(letterContent);
			letter.setReceiver(receiver);
			System.out.println("收信人"+receiver.getId()+receiver.getName());
			getLetterService().send(letter);
		
		}		
		
		
		try {
			System.out.println(projectId);
			
			
			ProjectComment projectComment=new ProjectComment();
			projectComment.setContent(projectCommentForm.getContent());
			projectComment.setTitle(projectCommentForm.getTitle());
			projectComment.setAuthor(user);
			projectComment.setProjectId(projectId);
			projectComment.setTime(date);
			
			if (user!=null&&user.getType()==UserConst.Type.JUDGER) {
				projectComment.setType(ProjectCommentConst.Type.PROFESSOR);
			} else {
					projectComment.setType(ProjectCommentConst.Type.NORMAL);
			}
		
			System.out.println("AddCommentAction test:"+projectComment.getTitle()+projectComment.getContent()+"s123adf");
			if (getProjectService().addComment( projectComment)) {
				request.setAttribute("message","success");
				
			}
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute("message", "fail");
		}
		
		return mapping.findForward("ajaxSuccessOrFailure");
	}
}