/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.project;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.Project;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.util.UserConst;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-25-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Web/testSuccess.jsp"
 */
public class DeleteCommentAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int commentId=Integer.parseInt(request.getParameter("commentId"));
		HttpSession session=request.getSession();
		int projectId=Integer.parseInt(request.getParameter("projectId"));
		Project project=getProjectService().getProject(projectId);
		User user=(User)session.getAttribute("user");
		if(user!=null){			
			if(project.getOwner().getId()==user.getId()||user.getType()==UserConst.Type.MANAGER){
				//管理员和用户可以删除评论
				if(getProjectService().deleteComments(commentId))
				return mapping.findForward("success");
				
				
			}
}
		
		return null;
	}
}