/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.project;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.User;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;



import common.Logger;

/** 
 * MyEclipse Struts
 * Creation date: 03-29-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ProFileAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	Logger logger=Logger.getLogger(getClass());
	//TODO AUTHORITY
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		User user = (User)request.getSession().getAttribute("user");
		int access = getAccess(user.getType());
		int pro_id =Integer.parseInt(request.getParameter("proId"));
		request.setAttribute("list",getFileInfoService().list_project(pro_id));
		return mapping.findForward("list");
	}
	
	private int getAccess(int type){

    	switch(type){
    	case 1:return 1;
    	case 2:return 2;
    	case 3:return 0;
    	case 4:return 4;
    	case 5:return 8;
    	case 6:return 16;
    	}
    		return 0;
		
	}
}