/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.project;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.action.BaseAction;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-01-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class StarAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{

			int id = Integer.parseInt(request.getParameter("projectId"));
		
			int starnum = Integer.parseInt(request.getParameter("star"));
			getProjectService().addStar(id,starnum);
			request.setAttribute("message", "success");
		}catch (Exception e) {
			request.setAttribute("message", e.getMessage());
		}

		return mapping.findForward("ajaxSuccessOrFailure");
	}
}