/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action.project;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.tiaozhanbei.action.BaseAction;
import net.tiaozhanbei.model.User;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class VoteAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int  projectId=Integer.valueOf(request.getParameter("projectId"));
		HttpSession session=request.getSession();
		
		User user=(User)session.getAttribute("user");
		user=getUserService().getUserById(user.getId());
		System.out.println("用户现在分数"+user.getScore());
		
		if(getProjectService().vote(projectId,user)){
			System.out.println("完成！");
			return mapping.findForward("ajax");
		}
			
		
				
		return mapping.findForward("error");
	}
}