/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2009
 * 
 * XDoclet definition:
 * @struts.form name="newVoteForm"
 */
public class NewVoteForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 3860789957549448515L;

	/** discription property */
	private String discription;

	/** type property */
	private int type;

	/** title property */
	private String title;

	/** choices property */
	private String[] choices;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the discription.
	 * @return String
	 */
	public String getDiscription() {
		return discription;
	}

	/** 
	 * Set the discription.
	 * @param discription The discription to set
	 */
	public void setDiscription(String discription) {
		this.discription = discription;
	}

	/** 
	 * Returns the type.
	 * @return int
	 */
	public int getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(int type) {
		this.type = type;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the choices.
	 * @return String[]
	 */
	public String[] getChoices() {
		return choices;
	}

	/** 
	 * Set the choices.
	 * @param choices The choices to set
	 */
	public void setChoices(String[] choices) {
		this.choices = choices;
	}
}