/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * @struts.form name="projectForm"
 */
public class ProjectForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 6269329567181599981L;

	/** detal property */
	private String detal;

	/** type property */
	private String type;

	/** brief property */
	private String brief;

	/** name property */
	private String name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the detal.
	 * @return String
	 */
	public String getDetal() {
		return detal;
	}

	/** 
	 * Set the detal.
	 * @param detal The detal to set
	 */
	public void setDetal(String detal) {
		this.detal = detal;
	}

	/** 
	 * Returns the type.
	 * @return Integer
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the brief.
	 * @return String
	 */
	public String getBrief() {
		return brief;
	}

	/** 
	 * Set the brief.
	 * @param brief The brief to set
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
}