/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-21-2009
 * 
 * XDoclet definition:
 * @struts.form name="userForm"
 */
public class UserForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sex property */
	private String sex;

	/** phone property */
	private String phone;

	/** authority property */
	private String authority;

	/** passwd property */
	private String passwd;

	/** realname property */
	private String realname;

	/** email property */
	private String email;

	/** name property */
	private String name;

	/** school property */
	private String school;

	/** company property */
	private String company;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the authority.
	 * @return String
	 */
	public String getAuthority() {
		return authority;
	}

	/** 
	 * Set the authority.
	 * @param authority The authority to set
	 */
	public void setAuthority(String authority) {
		this.authority = authority;
	}

	/** 
	 * Returns the passwd.
	 * @return String
	 */
	public String getPasswd() {
		return passwd;
	}

	/** 
	 * Set the passwd.
	 * @param passwd The passwd to set
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/** 
	 * Returns the realname.
	 * @return String
	 */
	public String getRealname() {
		return realname;
	}

	/** 
	 * Set the realname.
	 * @param realname The realname to set
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the school.
	 * @return String
	 */
	public String getSchool() {
		return school;
	}

	/** 
	 * Set the school.
	 * @param school The school to set
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/** 
	 * Returns the company.
	 * @return String
	 */
	public String getCompany() {
		return company;
	}

	/** 
	 * Set the company.
	 * @param company The company to set
	 */
	public void setCompany(String company) {
		this.company = company;
	}
}