/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.model.FileInfo;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class FileAction extends BaseAction {
	/*
	 * Generated Methods
	 */

    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        List<FileInfo> list=null;
        try {
            list = getFileInfoService().list_common();
        } catch (RuntimeException ex) {
            ex.printStackTrace();
            return mapping.findForward("error");
        }
            request.setAttribute("list", list);
            return mapping.findForward("success");
    }
}