/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.event.AutoLoginEvent;
import net.tiaozhanbei.model.Project;
import net.tiaozhanbei.model.User;
import net.tiaozhanbei.service.IProjectService.Order;
import net.tiaozhanbei.util.CommonResources;
import net.tiaozhanbei.util.Page;
import net.tiaozhanbei.util.datastruct.UrlTree;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ProjectsAction extends BaseAction {
	/*
	 * Generated Methods
	 */
	

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		if(request.getParameter("ajax")==null){
			UrlTree tree = UrlTree.load("projectCatagory", CommonResources.getProjectCatagoryBundle());
			request.setAttribute("catagoryTree", tree);
			
			return mapping.findForward("success");
		}
		else 
			return super.execute(mapping, form, request, response);
	}
	/** 
	 * 参数[orderBy=(rank|vote)][catalog=ProjectConst中的常量]
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String param = request.getParameter("page");
		Page<Project> resaultPage = new Page<Project>(param);


		
		Order order = Order.Default;
		param = request.getParameter("orderBy");
		if("rank".equals(param))
			order = Order.Rank;
		else if("vote".equals(param))
			order = Order.Vote;
		else if("visit".equals(param))
			order = Order.Visit;

		
		param = request.getParameter("catalog");
		getProjectService().fillProjectPage(order,param,resaultPage);
		
		
		request.setAttribute("page", resaultPage);
		System.out.print("Projects:"+resaultPage.getTotalCount());
		return mapping.findForward("list");
	}

	public ActionForward focus(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		publishEvent(new AutoLoginEvent(this,request));
		
		User user = (User)request.getSession().getAttribute("user");
		if(user != null){
	
			user = getUserService().getUserById(user.getId());
			request.setAttribute("interest", user.getInterestProjects());
		}
		return mapping.findForward("focus");
	}

}
