/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.model.Project;
import net.tiaozhanbei.util.CommonResources;
import net.tiaozhanbei.util.Page;
import net.tiaozhanbei.util.datastruct.UrlTree;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-02-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SearchInsideAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		String param = request.getParameter("page");
		String searchtext = request.getParameter("searchtext");
		Page<Project> resultPage = new Page<Project>(param);
		
		getProjectService().searchInside(searchtext, resultPage);
		request.setAttribute("page", resultPage);
		request.setAttribute("searchtext", searchtext);
		System.out.print("Projects:"+resultPage.getTotalCount());
		return mapping.findForward("searchResult");
	}
}