/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.Consts;
import net.tiaozhanbei.form.UserForm;
import net.tiaozhanbei.model.User;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-21-2009
 * 
 * XDoclet definition:
 * @struts.action path="/user" name="userForm" input="/User/Register.jsp" scope="request" validate="true"
 */
public class UserAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String action = request.getParameter("action");
		if (action.equals("Add")) {
			getUserService().reigesterUser((UserForm) form);
		}else {
			request.setAttribute("errorMessage", Consts.User.Error.strFailed);
			return mapping.findForward("error");
			
		}
		return mapping.findForward("success");
	}
}