/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package net.tiaozhanbei.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.tiaozhanbei.exception.DAOException;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-20-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class VoteAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 调查投票的ajaxAction
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			if("radio".equals( request.getParameter("type"))){
				String idString = request.getParameter("voteItemIds");
				if(idString != null){
					int id = Integer.parseInt(idString);
					getVoteService().vote(id);
				}
			}else {
				String[] ids = (String[])request.getParameterValues("voteItemIds");
				if(ids != null)
					for (int i = 0; i < ids.length; i++) {
				
						getVoteService().vote(Integer.parseInt(ids[i]));
				}
			}
			
			int voteId = Integer.parseInt(request.getParameter("id"));
			
			request.setAttribute("vote", getVoteService().getVote(voteId));
		} catch (DAOException e) {
			System.out.println(e);
			return mapping.findForward("error");
		}
		return mapping.findForward("vote");
	}
	
}